# Generated by Django 4.2.3 on 2023-07-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('year', models.IntegerField()),
                ('image', models.ImageField(upload_to='books/images')),
            ],
        ),
    ]
